# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='default',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='contentpost',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_category', to='posts.Category'),
        ),
    ]
