# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='published',
            field=models.DateField(default=datetime.datetime(2016, 1, 22, 1, 26, 30, 972519, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
