# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160325_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='categories',
            field=models.CharField(choices=[('News', 'News'), ('Entertainmet', 'Entertainmet'), ('Other', 'Other')], default='News', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
