# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160319_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='default',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='contentpost',
            name='categories',
            field=models.CharField(choices=[('News', 'News'), ('Entertainmet', 'Entertainmet'), ('Other', 'Other')], default='Entertainmet', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
