# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160325_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='default',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='contentpost',
            name='categories',
            field=models.CharField(choices=[('news', 'News'), ('entertainmet', 'Entertainmet'), ('other', 'Other')], default='Entertainmet', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
