# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_contentpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
