# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160326_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
