# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160319_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpost',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='width_field',
        ),
    ]
