# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.CharField(choices=[('Video-Reviews', 'Reviews'), ('Entertainmet', 'Entertainmet'), ('Other', 'Other')], default='Entertainmet', max_length=50),
        ),
    ]
