# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160211_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='description',
            new_name='content',
        ),
    ]
