# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category_slug',
            field=models.SlugField(default='Video'),
            preserve_default=False,
        ),
    ]
