# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.CharField(choices=[('Video-Reviews', 'Reviews'), ('Video', 'Video')], default='Video', max_length=50),
        ),
    ]
