# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.CharField(choices=[('video-reviews', 'Reviews'), ('video', 'Video')], default='Video', max_length=50),
        ),
    ]
