# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160328_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
