# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
