# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('N/A', 'Does it really matter?')], default='M', max_length=50, null=True)),
                ('cannabis_type', models.CharField(blank=True, choices=[('Sativa', 'Sativa'), ('Indica', 'Indica'), ('Hybrid', 'Hybrid')], default='Sativa', max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
