# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160321_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cannabis_type',
            field=models.CharField(blank=True, choices=[('Sativa', 'Sativa'), ('Indica', 'Indica'), ('Hybrid', 'Hybrid')], default='Sativa', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('N/A', 'Does it really matter?')], default='M', max_length=50, null=True),
        ),
    ]
