# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='full_name',
        ),
    ]
