# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 31, 0, 44, 40, 294454, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
