# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160312_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
