# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_productreview_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='productreview',
            name='category_slug',
            field=models.SlugField(default='other'),
            preserve_default=False,
        ),
    ]
