# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_productreview_user_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user_review',
        ),
    ]
