# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_productreview_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
