# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160319_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='category_slug',
        ),
    ]
