# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_productreview_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='category_slug',
            field=models.SlugField(default='Other'),
            preserve_default=False,
        ),
    ]
