# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_productreview_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.TextField(),
        ),
    ]
