# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20160320_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='concentrate_only',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='convenience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
